name: aerospike-server

environment:
  EEREPO: modules/ee
  CLIENTREPO_2X: modules/client

dependency:
  - url: git@github.com:citrusleaf/aerospike-server-enterprise
    dir: $EEREPO
  - url: git@github.com:citrusleaf/client
    dir: $CLIENTREPO_2X

container:
  - base:
      - 192.168.106.181/build/aerospike-server:centos-6
      - 192.168.106.181/build/aerospike-server:centos-7
      - 192.168.106.181/build/aerospike-server:debian-6
      - 192.168.106.181/build/aerospike-server:debian-7
      - 192.168.106.181/build/aerospike-server:debian-8
      - 192.168.106.181/build/aerospike-server:ubuntu-12.04
      - 192.168.106.181/build/aerospike-server:ubuntu-14.04

build:
  - name: community
    environment:
      EEREPO:
    script:
      - make
      - make $PKG
      - make tar
      - make source
    artifact:
      - pkg/packages/*
  - name: enterprise
    environment:
      EEREPO: /work/source/$EEREPO
      CLIENTREPO_2X: /work/source/$CLIENTREPO_2X
    script:
      - make -C $CLIENTREPO_2X
      - make +ee
      - make $PKG+ee
      - make source+ee
    artifact:
      - pkg/packages/*
  - name: enterprise+asm
    environment:
      EEREPO: /work/source/$EEREPO
      CLIENTREPO_2X: /work/source/$CLIENTREPO_2X
    script:
      - make -C $CLIENTREPO_2X
      - make asm+ee
      - make $PKG+ee USE_ASM=1
    artifact:
      - pkg/packages/*
      - target/Linux-x86_64/gen/mallocations.h
