#!/bin/bash
# Install Aerospike server on Debian6/Debian7/Ubuntu12.  
# This script must be run as root or sudo.

#------------------
# Process arguments
#------------------
if [ $# -eq 0 ]
then
	args="-i"
else
	args="$@"
fi

if [ $EUID -ne 0 ]
then
	echo "This script requires root or sudo privileges."
	exit 1
fi

#---------------
# Install server
#---------------
echo Installing server
dpkg $args aerospike-server-*.rpm

