#!/bin/bash
# Install Aerospike server on Debian6/Debian7/Ubuntu12.  
# This script must be run as root or sudo.

#------------------
# Verify User
#------------------

if [ $EUID -ne 0 ]
then
	echo "This script requires root or sudo privileges."
	exit 1
fi

#---------------
# Install server
#---------------
echo Installing server

# Use default arguments if none passed in.
if [ $# -eq 0 ]
then
	echo dpkg -i aerospike-server-*.deb
	dpkg -i aerospike-server-*.deb
else
	echo dpkg "$@" aerospike-server-*.deb
	dpkg "$@" aerospike-server-*.deb
fi

