#!/bin/bash
# Install Aerospike server on RHEL/Fedora/Centos 6.  
# This script must be run as root or sudo.

#------------------
# Verify User
#------------------

if [ $EUID -ne 0 ]
then
	echo "This script requires root or sudo privileges."
	exit 1
fi

#---------------
# Install server
#---------------
echo Installing server

# Use default arguments if none passed in.
if [ $# -eq 0 ]
then
	echo rpm -ivh aerospike-server-*.rpm
	rpm -ivh aerospike-server-*.rpm
else
	echo rpm "$@" aerospike-server-*.rpm
	rpm "$@" aerospike-server-*.rpm
fi

