#!/bin/bash
# Install Aerospike server on RHEL/Fedora/Centos 6.  
# This script must be run as root or sudo.

#------------------
# Process arguments
#------------------
if [ $# -eq 0 ]
then
	args="-ivh"
else
	args="$@"
fi

if [ $EUID -ne 0 ]
then
	echo "This script requires root or sudo privileges."
	exit 1
fi

#---------------
# Install server
#---------------
echo Installing server
rpm $args aerospike-server-*.rpm

